supply_now/pages/urls.py
from collections import namedtuple
from django.urls import path


from . import views

app_name = "pages"


urlpatterns = [
     #path('', views.HomePageView.as_view(), name='home'),
     path('', views.listar_produtos, name='home'),
     path('Produtos_Empresa', views.lista_prod_empre, name='listaProd'),
     path('Cadastro_Produtos', views.cadastrar_produtos, name='cad_prod'),
     path('editProduto/<int:id>', views.edit_cadastro, name="produto"),

    ]

supply_now/supply_now/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('', include('pages.urls', namespace='pages')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

supply_now/pages/models.py
from django.db import models
from django.contrib.auth.models import User

Status = (
    ("Sim", "Temos em Estoque"),
    ("Não", "Não temos em Estoque"),
)

class PRODUTO(models.Model):
    nome = models.CharField(max_length = 100)
    descricao = models.TextField()
    photo_prod = models.ImageField(upload_to = "img/%y")
    preco = models.DecimalField(max_digits = 10, decimal_places=2)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    status = models.CharField(
        max_length = 50,
        choices = Status,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

supply_now/pages/forms.py
from django import forms
from .models import PRODUTO


class formsProdutos(forms.ModelForm):

    class Meta:
        model = PRODUTO
        fields = ('nome','descricao',  'photo_prod', 'preco', 'user', 'status')

supply_now/pages/views.py
from .models import PRODUTO
from .forms import formsProdutos
from django.shortcuts import get_object_or_404, redirect, render

def listar_produtos(request):
    produtos = PRODUTO.objects.all()
    return render(request, 'home.html', {'produtos': produtos})

def cadastrar_produtos(request):
    form = formsProdutos()
    if request.method == "POST":
        form = formsProdutos(request.POST)

        if form.is_valid():
            

            nome = form.cleaned_data['nome']
            foto = form.cleaned_data['photo_prod']
            descricao = form.cleaned_data['descricao']
            preco = form.cleaned_data['preco']
            user = form.cleaned_data['user']
            status = form.cleaned_data['status']

            
            new_produto = PRODUTO(nome, descricao, foto, preco, user, status)
            new_produto.save()
            return redirect('listaProd')

    else:

        form = formsProdutos()
        return render(request, 'produtos/produtos_cadastro.html', {'form': form})

def lista_prod_empre(request):
    produtos = PRODUTO.objects.all()
    return render(request, 'produtos/lista_produtos_empresa.html',   {'produtos': produtos})

def edit_cadastro(request, id):
    produto = get_object_or_404(PRODUTO, id)
    form = formsProdutos(instance=produto)

    if(request.method == 'POST'):
        return False

    else:
        return render(request, 'produtos/edit_produto.html', {'form': form, 'produto': produto})

supply_now/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Supply Now</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:listaProd' %}">Produtos</a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>

                    
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>

                   

                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

supply_now/templates/home.html
{% extends 'base.html' %}

{% block title %}Supply{% endblock %}

{% block content %}
    {% for prod in produtos %}
    <div>
        <p>{{prod.nome}}</p>
        <p>R${{prod.preco}}</p>
        <img src="{{ prod.photo_prod.url }}">
    </div>
    {% endfor %}
{% endblock %}
© 2021 Devil Ops, Inc.

supply_now/templates/produtos/delete_produto.html
{% extends 'base.html' %}

{% block title %}Deletar Produtos{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">

        {% csrf_token %}
        {{ form|crispy }}

        <button class="btn btn-btn-success" type="submit">Cadastrar</button>

    </form>

{% endblock %}

supply_now/templates/produtos/edit_produto.html
{% extends 'base.html' %}

{% block title %}Editar Produtos{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
  
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-btn-success" type="submit">Cadastrar</button>
    </form>
{% endblock %}

supply_now/templates/produtos/lista_produtos_empresa.html
{% extends 'base.html' %}

{% block title %}Supply - Lista de Produtos Empresa{% endblock %}

{% block content %}
    <a class="navbar-brand" href="{% url 'pages:cad_prod' %}">Cadastrar Produtos</a>
    {% for prod in produtos %}
    <div>
        <img src="{{ prod.photo_prod.url }}">
        <p>{{prod.nome}}</p>
        <p>R${{prod.preco}}</p>
        <a href="editProduto/{{prod.id}}">Editar</a>
    </div>
    {% endfor %}
{% endblock %}
© 2021 Supply, Inc.

supply_now/templates/produtos/produtos_cadastro.html
{% extends 'base.html' %}

{% block title %}Cadastro de Produtos{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
  
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-btn-success" type="submit">Cadastrar</button>
    </form>
{% endblock %}